<?php
/**
 * @category   Code2stay
 * @package    Code2stay_Importproduct
 * @author     rajnitish625@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Code2stay\Importproduct\Model\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

/**
 * Item status functionality model
 */
class Status implements OptionSourceInterface
{
    /**
     * Return array of assets
     *
     * @return array
     */
    public function toOptionArray()
    {
        return [
            ['label' => 'Asset A', 'value' => 'asset_a'],
            ['label' => 'Asset B', 'value' => 'asset_b'],
            ['label' => 'Asset C', 'value' => 'asset_c'],
            // Add more assets if needed
        ];
    }
}
