<?php
/**
 * @category   Code2stay
 * @package    Code2stay_Importproduct
 * @author     rajnitish625@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Code2stay\Importproduct\Model\ResourceModel;

class Importproduct extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('code2stay_importproduct', 'importproduct_id');   //here "code2stay_importproduct" is table name and "importproduct_id" is the primary key of custom table
    }
}
