<?php
/**
 * @category   Code2stay
 * @package    Code2stay_Importproduct
 * @author     rajnitish625@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Code2stay\Importproduct\Block\Adminhtml\Items\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        array $data = []
    ) {
        $this->_wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Import Products');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Import Products');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_code2stay_importproduct_items');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('item_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Upload Your csv File Here')]);
    
        // Add hidden field for importproduct_id if the model has an ID
        if ($model->getId()) {
            $fieldset->addField('importproduct_id', 'hidden', ['name' => 'importproduct_id']);
        }
    
        // Add CSV File Upload Field
        $fieldset->addField(
            'csv_file', // Corrected the name to 'csv_file', no spaces
            'file',
            [
                'name' => 'csv_file', // The name attribute here should match the file input field's name in HTML
                'label' => __('Import Your Products Here'),
                'title' => __('CSV File'),
                'required' => true
            ]
        );
    
        // Add Download Sample CSV Link
        $fieldset->addField(
            'sample_csv_download',
            'note',
            [
                'text' => __(
                    '<a href="%1" target="_blank">Download Sample CSV File</a>',
                    $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'sampledata.csv' // Correct URL
                )
            ]
        );
        
    
        // Set the model data for the form
        $form->setValues($model->getData());
        $this->setForm($form);
    
        return parent::_prepareForm();
    }
}
